spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=inventorydb
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: SA
    password: UGFzc3dvcmRAMTIz
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  platform:
    hibernate.dialect: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka
