spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventory_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
jpa:
  database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    org:
     hibernate: DEBUG
   

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka
